Lazily evaluate log message parameters
betcode-org/betfair pull request #530
Opened 2023-08-15 13:31 UTC by petedmarsh

Logging like this:

    logger.debug("Hello, %s" % name)

causes the message string to always be interpolated even if the message is not going to be logged.

Logging like this:

    logger.debug("Hello, %s", name)

will mean the string is only ever interpolated if it will be logged.

In practice here this will make little difference if the log level is INFO
or above, but it does mean a `if` statement can be removed from StreamListener.

See:

https://docs.python.org/3/howto/logging.html#optimization https://stackoverflow.com/questions/4148790/lazy-logger-message-string-evaluation

2023-08-16 07:48 UTC, liampauling commented
How does this compare to `f` strings?

2023-08-16 08:33 UTC, petedmarsh commented
f-strings would also be eagerly evaluated, to have lazy interpolation of the log messages the best way is to use %-style formatting and pass the arguments to the logger methods

2023-09-07 12:18 UTC, liampauling requested changes
black fmt

2023-09-07 12:22 UTC, petedmarsh commented
@liampauling I've formatted the code

2023-09-07 12:25 UTC, liampauling commented
thanks, test failing

2023-09-07 19:22 UTC, petedmarsh commented
@liampauling I've fixed the test, sorry!

2023-09-11 13:40 UTC, liampauling approved these changes

2023-09-11 13:40 UTC, merged